name: Build Python package

on:
   workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                python-version: "3.10"
            - name: Install dependencies
              run: |
                python -m pip install -U pip
                pip install -U setuptools wheel twine                
            - name: Build package
              run: |
                python setup.py sdist bdist_wheel
            - name: Publish package
              run: |
                python -m pip install twine
                python -m twine upload --repository pypi dist/*