name: Create Pypi package

on:
    push:
        branches:
            - main
            - master
            - demo

jobs:
    run_unit_tests:
        uses: arubenruben/portuguese_vid/.github/workflows/run_unit_tests.yml@demo
    build_python_package:
        uses: arubenruben/portuguese_vid/.github/workflows/build_python_package.yml@demo
        needs: run_unit_tests
    
    # Create a release
    publish_pypi_package:
        needs: [build_python_package]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                python-version: 3.10
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -U wheel setuptools twine
            - name: |
                Build and publish package
              uses: pypa/gh-action-pypi-publish@v1.5.0
              with:
                user: __token__
                password: ${{ secrets.PYPI_KEY }}